spring:
  profiles:
    active: local
  application:
    name: drawio-backend
  # Spring Session é…ç½®
  session:
    store-type: redis  # ä½¿ç”¨ Redis å­˜å‚¨ Session
    timeout: 604800     # Session è¿‡æœŸæ—¶é—´: 7å¤© (å•ä½:ç§’)
    redis:
      namespace: spring:session:drawio  # Redis key çš„å‘½åç©ºé—´
  # Redis é…ç½®
  data:
    redis:
      password: E628L1..3K220
      host: 47.95.35.178
      port: 6379
      database: 4
      # è¿æ¥æ± é…ç½®
      lettuce:
        observation:
          enabled: false # ğŸ›‘ å½»åº•å…³é—­ Lettuce çš„è§‚æµ‹æ€§
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms
server:
  port: 8081
  servlet:
    context-path: /api
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0

# springdoc-openapié¡¹ç›®é…ç½®
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.wfh.drawio.controller
# knife4jçš„å¢å¼ºé…ç½®ï¼Œä¸éœ€è¦å¢å¼ºå¯ä»¥ä¸é…
knife4j:
  enable: false
  setting:
    language: zh_cn

drawio:
  internal-token: wfh-drawio-internal-secret-8888
